apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: graphql
  name: graphql
spec:
  replicas: 1
  selector:
    matchLabels:
      service: graphql
  strategy: {}
  template:
    metadata:
      labels:
        service: graphql
    spec:
      containers:
        - args:
            - bash
            - -c
            - "prefect-server database upgrade -y && python src/prefect_server/services/graphql/server.py"
          env:
            - name: PREFECT_SERVER__DATABASE__CONNECTION_URL
              value: postgresql://prefect:prefect@postgres:5432/prefect_server
            - name: PREFECT_SERVER__HASURA__ADMIN_SECRET
              value: hasura-secret-admin-secret
            - name: PREFECT_SERVER__HASURA__HOST
              value: hasura
            - name: PREFECT_SERVER__SERVICES__HOST
              value: 0.0.0.0
          image: prefecthq/server:latest
          imagePullPolicy: "Always"
          name: graphql
          ports:
            - containerPort: 4201
          resources: {}
      restartPolicy: Always
      serviceAccountName: "prefect"
      volumes: null
status: {}
