apiVersion: v1
kind: Service
metadata:
  labels:
    service: hasura
  name: hasura
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    service: hasura
status:
  loadBalancer: {}
