apiVersion: v1
kind: ServiceAccount
metadata:
  name: prefect
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prefect-role
  labels:
    app.kubernetes.io/component: agent
rules:
  - apiGroups:
      - batch
      - extensions
    resources:
      - jobs
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prefect-role-binding
  labels:
    app.kubernetes.io/component: agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prefect-role
subjects:
  - kind: ServiceAccount
    name: prefect
